# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import Iterable as typing___Iterable
from typing import Optional as typing___Optional
from typing import Text as typing___Text
from typing import Union as typing___Union

from google.protobuf.descriptor import Descriptor as google___protobuf___descriptor___Descriptor
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode

class TemporaryExposureKeyExport(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    start_timestamp = ...  # type: builtin___int
    end_timestamp = ...  # type: builtin___int
    region = ...  # type: typing___Text
    batch_num = ...  # type: builtin___int
    batch_size = ...  # type: builtin___int
    @property
    def signature_infos(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        global___SignatureInfo
    ]: ...
    @property
    def keys(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        global___TemporaryExposureKey
    ]: ...
    def __init__(
        self,
        *,
        start_timestamp: typing___Optional[builtin___int] = None,
        end_timestamp: typing___Optional[builtin___int] = None,
        region: typing___Optional[typing___Text] = None,
        batch_num: typing___Optional[builtin___int] = None,
        batch_size: typing___Optional[builtin___int] = None,
        signature_infos: typing___Optional[typing___Iterable[global___SignatureInfo]] = None,
        keys: typing___Optional[typing___Iterable[global___TemporaryExposureKey]] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TemporaryExposureKeyExport: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TemporaryExposureKeyExport: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "batch_num",
            b"batch_num",
            "batch_size",
            b"batch_size",
            "end_timestamp",
            b"end_timestamp",
            "region",
            b"region",
            "start_timestamp",
            b"start_timestamp",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "batch_num",
            b"batch_num",
            "batch_size",
            b"batch_size",
            "end_timestamp",
            b"end_timestamp",
            "keys",
            b"keys",
            "region",
            b"region",
            "signature_infos",
            b"signature_infos",
            "start_timestamp",
            b"start_timestamp",
        ],
    ) -> None: ...

global___TemporaryExposureKeyExport = TemporaryExposureKeyExport

class SignatureInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    app_bundle_id = ...  # type: typing___Text
    android_package = ...  # type: typing___Text
    verification_key_version = ...  # type: typing___Text
    verification_key_id = ...  # type: typing___Text
    signature_algorithm = ...  # type: typing___Text
    def __init__(
        self,
        *,
        app_bundle_id: typing___Optional[typing___Text] = None,
        android_package: typing___Optional[typing___Text] = None,
        verification_key_version: typing___Optional[typing___Text] = None,
        verification_key_id: typing___Optional[typing___Text] = None,
        signature_algorithm: typing___Optional[typing___Text] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> SignatureInfo: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> SignatureInfo: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "android_package",
            b"android_package",
            "app_bundle_id",
            b"app_bundle_id",
            "signature_algorithm",
            b"signature_algorithm",
            "verification_key_id",
            b"verification_key_id",
            "verification_key_version",
            b"verification_key_version",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "android_package",
            b"android_package",
            "app_bundle_id",
            b"app_bundle_id",
            "signature_algorithm",
            b"signature_algorithm",
            "verification_key_id",
            b"verification_key_id",
            "verification_key_version",
            b"verification_key_version",
        ],
    ) -> None: ...

global___SignatureInfo = SignatureInfo

class TemporaryExposureKey(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    key_data = ...  # type: builtin___bytes
    transmission_risk_level = ...  # type: builtin___int
    rolling_start_interval_number = ...  # type: builtin___int
    rolling_period = ...  # type: builtin___int
    def __init__(
        self,
        *,
        key_data: typing___Optional[builtin___bytes] = None,
        transmission_risk_level: typing___Optional[builtin___int] = None,
        rolling_start_interval_number: typing___Optional[builtin___int] = None,
        rolling_period: typing___Optional[builtin___int] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TemporaryExposureKey: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TemporaryExposureKey: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "key_data",
            b"key_data",
            "rolling_period",
            b"rolling_period",
            "rolling_start_interval_number",
            b"rolling_start_interval_number",
            "transmission_risk_level",
            b"transmission_risk_level",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "key_data",
            b"key_data",
            "rolling_period",
            b"rolling_period",
            "rolling_start_interval_number",
            b"rolling_start_interval_number",
            "transmission_risk_level",
            b"transmission_risk_level",
        ],
    ) -> None: ...

global___TemporaryExposureKey = TemporaryExposureKey

class TEKSignatureList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def signatures(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        global___TEKSignature
    ]: ...
    def __init__(
        self, *, signatures: typing___Optional[typing___Iterable[global___TEKSignature]] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TEKSignatureList: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TEKSignatureList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["signatures", b"signatures"]
    ) -> None: ...

global___TEKSignatureList = TEKSignatureList

class TEKSignature(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    batch_num = ...  # type: builtin___int
    batch_size = ...  # type: builtin___int
    signature = ...  # type: builtin___bytes
    @property
    def signature_info(self) -> global___SignatureInfo: ...
    def __init__(
        self,
        *,
        signature_info: typing___Optional[global___SignatureInfo] = None,
        batch_num: typing___Optional[builtin___int] = None,
        batch_size: typing___Optional[builtin___int] = None,
        signature: typing___Optional[builtin___bytes] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TEKSignature: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TEKSignature: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "batch_num",
            b"batch_num",
            "batch_size",
            b"batch_size",
            "signature",
            b"signature",
            "signature_info",
            b"signature_info",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "batch_num",
            b"batch_num",
            "batch_size",
            b"batch_size",
            "signature",
            b"signature",
            "signature_info",
            b"signature_info",
        ],
    ) -> None: ...

global___TEKSignature = TEKSignature
